In [1]:
for n in range(1,5):
    print(n)

1
2
3
4


In [2]:
'''abcd's'''

"abcd's"

In [5]:
"it\'s mine"

"it's mine"

In [8]:
text = "Hello!"
print(text[:3])

Hel


In [10]:
double = 2**5
share = 10//2
print(double)
print(share)

32
5


In [11]:
dic = {"key1" : 0, "key2" : "abc", "key3" : [5,6] }
print(dic["key2"])
dic["new"] = '2'
print(dic)

abc
{'key1': 0, 'key2': 'abc', 'key3': [5, 6], 'new': '2'}


In [14]:
score = 60
if score > 70 :
    print("ok")
elif score > 60 and score <=70 :
    print("not now")
else :
    print("no")

no


In [16]:
score_list=['A','B','C','D','F']
myscore = 'C'
if myscore in score_list[:1]:
    print('pass')
elif myscore == score_list[2]:
    print('retake')
else:
    print('fail')

retake


In [17]:
num_list = [(1,2),(3,4),(5,6)]
for (first, second) in num_list:
    print(first+second)

3
7
11


In [19]:
bb_list = [2,3,4,5,6]
even = [num for num in bb_list if num%2 == 0]
even

[2, 4, 6]

In [20]:
def udf_01(x=3):
    return x + 10

In [22]:
udf_01()

13

In [4]:
import numpy as np

In [24]:
np.array([1,2,3,4]).reshape([2,2])

array([[1, 2],
       [3, 4]])

In [25]:
array = np.array([[1,2,3],[4,5,6]])
array[0,:2]

array([1, 2])

In [27]:
print(array.ndim)
print(array.shape)
print(array.dtype)

2
(2, 3)
int64


In [33]:
array.sum(), array.mean(), array.std() #array. tab 누르고 확인해보기

(21, 3.5, 1.707825127659933)

In [42]:
nums = np.array([1,2,2,3])
set(nums) #집합

{1, 2, 3}

In [43]:
np.unique(nums),len(nums)

(array([1, 2, 3]), 4)

In [44]:
np.arange(3,9,2)

array([3, 5, 7])

In [41]:
np.where(nums == 2,1,0) #np.where(nums == 2, "ok", "no")

array([0, 1, 1, 0])

In [5]:
import pandas as pd

In [47]:
ser = pd.Series([1,2,3])
ser

0    1
1    2
2    3
dtype: int64

In [48]:
ser.values

array([1, 2, 3])

In [49]:
ser.index

RangeIndex(start=0, stop=3, step=1)

In [50]:
ser2 = pd.Series([1,2,3], index=["a","b","c"])
ser2

a    1
b    2
c    3
dtype: int64

In [51]:
ser.skew() #왜도

0.0

In [52]:
ser.kurt() #첨도

nan

In [53]:
ser.idxmax() #맥스 값의 위치

2

In [54]:
ser.isin([1,2])

0     True
1     True
2    False
dtype: bool

In [57]:
df = pd.DataFrame([1,2,2],[3,3,4])
df

0
3  1
3  2
4  2

In [6]:
df = pd.DataFrame({"aa": [1,2,3], "bb":[2,3,4]}, ['a','b','c'])
df

aa  bb
a   1   2
b   2   3
c   3   4

In [7]:
df.aa

a    1
b    2
c    3
Name: aa, dtype: int64

In [8]:
df["aa"]

a    1
b    2
c    3
Name: aa, dtype: int64

In [9]:
df["aa"][:2]

a    1
b    2
Name: aa, dtype: int64

In [10]:
df.iloc[:,0]

a    1
b    2
c    3
Name: aa, dtype: int64

In [11]:
df.loc[:,"aa"]

a    1
b    2
c    3
Name: aa, dtype: int64

In [64]:
df.iloc[:2,:]

aa  bb
0   1   2
1   2   3

In [65]:
df.iloc[:,0]

0    1
1    2
2    3
Name: aa, dtype: int64

In [66]:
df.loc[:,"aa"]

0    1
1    2
2    3
Name: aa, dtype: int64

In [69]:
pd.crosstab(df['aa'],df['bb']) #normalize인자에 true,1,0 값을 이용하여 정규화

bb  2  3  4
aa         
1   1  0  0
2   0  1  0
3   0  0  1

In [12]:
df2 = pd.DataFrame([[1,2],[3,4],[5,6]], columns = ["xx","yy"], index=['a','b','c'])
df2

xx  yy
a   1   2
b   3   4
c   5   6

In [68]:
df3 = pd.DataFrame(np.arange(4).reshape((2,2)), columns = ["a", "b"])
df3

a  b
0  0  1
1  2  3