In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error

In [3]:
df = pd.read_csv("mobiles.csv")
df.head()

screen_size  ROM  RAM  num_rear_camera  num_front_camera  battery_capacity  \
0  Very Small   64    2                1                 1              1800   
1       Small   64    4                2                 1              2815   
2  Very Small   64    2                1                 1              1800   
3      Medium   64    3                1                 1              2942   
4      Medium  128    4                2                 1              2815   

   ratings  num_of_ratings  sales_price  discount_percent   sales  
0      4.5           38645        32999              0.17  127.52  
1      4.5             244        57149              0.04    1.39  
2      4.5           38645        32999              0.17  127.52  
3      4.6            5366        42999              0.10   23.07  
4      4.6             745        69149              0.02    5.15

In [4]:
#Q1

In [6]:
#1 sales 이상치 구하기

In [11]:
df[df['sales'].isna()]

Empty DataFrame
Columns: [screen_size, ROM, RAM, num_rear_camera, num_front_camera, battery_capacity, ratings, num_of_ratings, sales_price, discount_percent, sales]
Index: []

In [18]:
avg = df['sales'].mean()
std = df['sales'].std()

In [20]:
df_1 = df[df['sales'] > avg + 2*std]

In [89]:
df.loc[df['sales'] > avg + 2*std,].reset_index(drop=True)

screen_size  ROM  RAM  num_rear_camera  num_front_camera  battery_capacity  \
0       Medium  128    6                2                 1              4000   
1        Large  128    6                4                 2              4500   
2        Large   32    2                2                 1              5000   
3        Large   32    2                2                 1              5000   
4       Medium   16    2                2                 1              4000   
5       Medium   32    2                2                 1              4000   
6       Medium   16    2                2                 1              4000   
7       Medium   64    4                2                 2              4000   
8       Medium   64    6                2                 1              4000   
9        Small   32    3                1                 1              4100   
10      Medium   64    4                1                 1              4000   
11      Medium   64    4                2                 1              4000   
12      Medium   64    6                2                 1              4000   
13      Medium   64    4                2                 2              4000   
14      Medium   64    4                2                 1              4000   
15       Small   64    4                2                 1              3080   

    ratings  num_of_ratings  sales_price  discount_percent   sales  
0       4.6          122001        18999              0.09  231.79  
1       4.5          267028        15999              0.20  427.22  
2       4.4          223672         7499              0.16  167.73  
3       4.4          223672         7499              0.16  167.73  
4       4.4          226996         6499              0.07  147.52  
5       4.4          226996         6999              0.12  158.87  
6       4.4          226996         6499              0.07  147.52  
7       4.5          125016        12459              0.22  155.76  
8       4.5          129661        13500              0.20  175.04  
9       4.4          642373         8565              0.04  550.19  
10      4.4          357064        10999              0.04  392.73  
11      4.5          141177        14450              0.03  204.00  
12      4.5          129661        13400              0.13  173.75  
13      4.5          125016        13990              0.12  174.90  
14      4.5          141177        12900              0.04  182.12  
15      4.4          470905        10490              0.25  493.98

In [22]:
(df_1['ROM']/32 + df_1['RAM']/2 + df_1['num_rear_camera'] + df_1['num_front_camera'] + df_1['battery_capacity']/1000).mean()

11.01125

In [23]:
#Q2

In [24]:
#df.corr(method=pearson)

In [92]:
df['num_rear_camera'].unique()

array([1, 2, 3, 4])

In [93]:
df_2 = df.loc[df['num_rear_camera']!=1,('battery_capacity','ratings','num_of_ratings','sales')]
df_2.head()

battery_capacity  ratings  num_of_ratings  sales
1              2815      4.5             244   1.39
4              2815      4.6             745   5.15
5              2815      4.6             745   4.78
6              2815      4.6             745   5.15
7              2815      4.6             745   4.78

In [100]:
df_2.corr(method = 'pearson').replace(1,np.nan).loc['sales',:].abs().round(2).max()

0.95

In [105]:
df_22 = df_2.corr(method = 'pearson').reset_index().melt(id_vars = 'index')
df_22.loc[df_22['index']!=df_22['variable']].groupby('index').max().round(2).reset_index()

index variable  value
0  battery_capacity    sales   0.03
1    num_of_ratings    sales   0.95
2           ratings    sales   0.23
3             sales  ratings   0.95

In [35]:
#Q3

In [36]:
#K-NN RMSE 기준 가장 성능이 좋은 모델, 모델의 k개수

In [37]:
df.head()

screen_size  ROM  RAM  num_rear_camera  num_front_camera  battery_capacity  \
0  Very Small   64    2                1                 1              1800   
1       Small   64    4                2                 1              2815   
2  Very Small   64    2                1                 1              1800   
3      Medium   64    3                1                 1              2942   
4      Medium  128    4                2                 1              2815   

   ratings  num_of_ratings  sales_price  discount_percent   sales  
0      4.5           38645        32999              0.17  127.52  
1      4.5             244        57149              0.04    1.39  
2      4.5           38645        32999              0.17  127.52  
3      4.6            5366        42999              0.10   23.07  
4      4.6             745        69149              0.02    5.15

In [38]:
df['screen_size'].unique()

array(['Very Small', 'Small', 'Medium', 'Large', 'Very Large'],
      dtype=object)

In [51]:
df_3 = df.copy()

In [45]:
#df_3.loc[:,'screen_size'] =df_3['screen_size'].apply(lambda x: 0 if x == 'Very Small' else (1 if x == 'Small' else (2 if x == 'Medium' else (3 if x == 'Large' else 4))) )

In [52]:
df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 430 entries, 0 to 429
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   screen_size       430 non-null    object 
 1   ROM               430 non-null    int64  
 2   RAM               430 non-null    int64  
 3   num_rear_camera   430 non-null    int64  
 4   num_front_camera  430 non-null    int64  
 5   battery_capacity  430 non-null    int64  
 6   ratings           430 non-null    float64
 7   num_of_ratings    430 non-null    int64  
 8   sales_price       430 non-null    int64  
 9   discount_percent  430 non-null    float64
 10  sales             430 non-null    float64
dtypes: float64(3), int64(7), object(1)
memory usage: 37.1+ KB


In [54]:
df_3 = pd.get_dummies(df_3)

In [107]:
df_3_dummies = pd.get_dummies(df, columns = ['screen_size'], dtype = 'int')
df_3_dummies.head()

ROM  RAM  num_rear_camera  num_front_camera  battery_capacity  ratings  \
0   64    2                1                 1              1800      4.5   
1   64    4                2                 1              2815      4.5   
2   64    2                1                 1              1800      4.5   
3   64    3                1                 1              2942      4.6   
4  128    4                2                 1              2815      4.6   

   num_of_ratings  sales_price  discount_percent   sales  screen_size_Large  \
0           38645        32999              0.17  127.52                  0   
1             244        57149              0.04    1.39                  0   
2           38645        32999              0.17  127.52                  0   
3            5366        42999              0.10   23.07                  0   
4             745        69149              0.02    5.15                  0   

   screen_size_Medium  screen_size_Small  screen_size_Very Large  \
0                   0                  0                       0   
1                   0                  1                       0   
2                   0                  0                       0   
3                   1                  0                       0   
4                   1                  0                       0   

   screen_size_Very Small  
0                       1  
1                       0  
2                       1  
3                       0  
4                       0

In [55]:
df_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 430 entries, 0 to 429
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   ROM                     430 non-null    int64  
 1   RAM                     430 non-null    int64  
 2   num_rear_camera         430 non-null    int64  
 3   num_front_camera        430 non-null    int64  
 4   battery_capacity        430 non-null    int64  
 5   ratings                 430 non-null    float64
 6   num_of_ratings          430 non-null    int64  
 7   sales_price             430 non-null    int64  
 8   discount_percent        430 non-null    float64
 9   sales                   430 non-null    float64
 10  screen_size_Large       430 non-null    uint8  
 11  screen_size_Medium      430 non-null    uint8  
 12  screen_size_Small       430 non-null    uint8  
 13  screen_size_Very Large  430 non-null    uint8  
 14  screen_size_Very Small  430 non-null    ui

In [108]:
df_3.shape

(430, 15)

In [56]:
#data = df_3.drop('sales',axis = 1)
#value = df_3['sales']

In [57]:
#x_train, x_test, y_train, y_test = train_test_split(data, value, test_size = 0.2, random_state = 123)

In [138]:
df_3 = df_3.set_index('sales').reset_index()
df_train, df_test = train_test_split(df_3, train_size = 0.8, random_state=123)
len(df_train),len(df_test)

(344, 86)

In [65]:
#scaler = MinMaxScaler()
#scaler.fit(x_train)

MinMaxScaler()

In [113]:
model_nor = MinMaxScaler().fit(df_train)
arr_train_nor = model_nor.transform(df_train)
arr_test_nor = model_nor.transform(df_test)

In [66]:
#x_train_scd = scaler.transform(x_train)
#x_test_scd = scaler.transform(x_test)

In [63]:
#y_train

410      1.95
21      25.76
223     13.81
79      19.53
264     18.77
        ...  
230     30.81
98     231.79
322      0.02
382    175.04
365      0.26
Name: sales, Length: 344, dtype: float64

In [68]:
from sklearn.metrics import mean_squared_error, r2_score

In [130]:
ls_k = [3,5,7,9,11]
ls_rmse = []
for k in ls_k: 
    knn_regressor = KNeighborsRegressor(n_neighbors=k)
    #knn_regressor.fit(x_train_scd, y_train)
    knn_regressor.fit(X = arr_train_nor[:,1:],y = arr_train_nor[:,0])
    pred = knn_regressor.predict(arr_test_nor[:,1:])
    val_rmse = mean_squared_error(y_true = arr_test_nor[:,0], y_pred = pred)**0.5
    #predictions = knn_regressor.predict(x_test_scd)
    #print('score : ', knn_regressor.score(x_test_scd, y_test))
    #print('rmse : ', np.sqrt(mean_squared_error(y_test, predictions)))
    ls_rmse.append(val_rmse) #ls_rmse = ls_rmse + [val_rmse]
    print('rmse : ', val_rmse)

rmse :  0.08186677375964535
rmse :  0.09879109824384892
rmse :  0.107669855645971
rmse :  0.11232111394853059
rmse :  0.1136902366621185


In [132]:
best_k = pd.Series(ls_rmse, index = ls_k).idxmin()
best_k

3

In [70]:
#Q4

In [80]:
#single_test_data = [[256,6,4,1,4000,4.3,25000,85000,0.05,1,0,0,0,0]]
#t = pd.DataFrame(single_test_data, columns = ['ROM','RAM','num_rear_camera','num_front_camera','battery_capacity', 'ratings','num_of_ratings','sales_price','discount_percent',
#                           'screen_size_Large','screen_size_Medium','screen_size_Small','screen_size_Very Large','screen_size_Very Small'])

In [126]:
df_4 = df_test.head(1).reset_index(drop=True)
df_4

sales  ROM  RAM  num_rear_camera  num_front_camera  battery_capacity  \
0    5.9  256    4                2                 1              2815   

   ratings  num_of_ratings  sales_price  discount_percent  screen_size_Large  \
0      4.6             745        79149              0.02                  0   

   screen_size_Medium  screen_size_Small  screen_size_Very Large  \
0                   1                  0                       0   

   screen_size_Very Small  
0                       0

In [133]:
df_4_nor = model_nor.transform(df_4)
df_4_nor

array([[0.0119438 , 0.49206349, 0.27272727, 0.33333333, 0.        ,
        0.19519231, 1.        , 0.00157358, 0.47953795, 0.02325581,
        0.        , 1.        , 0.        , 0.        , 0.        ]])

In [137]:
knn_optimal = KNeighborsRegressor(n_neighbors=best_k)
knn_optimal.fit(X = arr_train_nor[:,1:],y = arr_train_nor[:,0])


KNeighborsRegressor(n_neighbors=3)

In [136]:
knn_optimal.predict(df_4)

/Users/cherylkim/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:443: UserWarning: X has feature names, but KNeighborsRegressor was fitted without feature names
  warnings.warn(


array([0.09333333])

In [139]:
pred_best = knn_optimal.predict(df_4_nor[:,1:])
pred_best

array([0.0119438])

In [140]:
#역변환!
df_4_nor[0,0] = pred_best

In [141]:
arr_t1_inv = model_nor.inverse_transform(df_4_nor)
df_t1_inv = pd.DataFrame(arr_t1_inv, columns = df_4.columns)
df_t1_inv

sales    ROM  RAM  num_rear_camera  num_front_camera  battery_capacity  \
0    5.9  256.0  4.0              2.0               1.0            2815.0   

   ratings  num_of_ratings  sales_price  discount_percent  screen_size_Large  \
0      4.6           745.0      79149.0              0.02                0.0   

   screen_size_Medium  screen_size_Small  screen_size_Very Large  \
0                 1.0                0.0                     0.0   

   screen_size_Very Small  
0                     0.0