In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("sales_pos.csv")
df.head()

user       prod gender age_group  job city  marital  prod_cat1  prod_cat2  \
0     1  P00069042      F      0-17   10    A        0          3        NaN   
1     1  P00248942      F      0-17   10    A        0          1        6.0   
2     1  P00087842      F      0-17   10    A        0         12        NaN   
3     1  P00085442      F      0-17   10    A        0         12       14.0   
4     2  P00285442      M       55+   16    C        0          8        NaN   

   prod_cat3  purchase  
0        NaN      8370  
1       14.0     15200  
2        NaN      1422  
3        NaN      1057  
4        NaN      7969

In [3]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

In [4]:
#q1

In [7]:
popular_prod = df.groupby('prod')['purchase'].sum().idxmax()
popular_prod

'P00025442'

In [9]:
df.groupby('job')['prod'].count().idxmax()

4

In [10]:
#q2

In [14]:
df.marital.unique()

array([0, 1])

In [44]:
df_1 = df.loc[df['age_group'] == '26-35',('user','marital','prod_cat1','prod_cat2','prod_cat3')].fillna(0).reset_index()
df_1.head()

index  user  marital  prod_cat1  prod_cat2  prod_cat3
0      5     3        0          1        2.0        0.0
1      9     5        1          8        0.0        0.0
2     10     5        1          5       11.0        0.0
3     11     5        1          8        0.0        0.0
4     12     5        1          8        0.0        0.0

In [167]:
df_1.sort_values(['prod_cat1','prod_cat2','prod_cat3'])

index  user  marital  prod_cat1  prod_cat2  prod_cat3 category
190        519    93        1          1          0          0    1-0-0
195        524    93        1          1          0          0    1-0-0
224        660   129        0          1          0          0    1-0-0
280        826   149        1          1          0          0    1-0-0
390       1086   184        1          1          0          0    1-0-0
...        ...   ...      ...        ...        ...        ...      ...
219580  550056  6022        0         20          0          0   20-0-0
219582  550058  6024        1         20          0          0   20-0-0
219584  550061  6029        1         20          0          0   20-0-0
219585  550064  6035        0         20          0          0   20-0-0
219586  550065  6036        1         20          0          0   20-0-0

[219587 rows x 7 columns]

In [168]:
df_1.drop_duplicates().shape()

TypeError: 'tuple' object is not callable

In [49]:
df_1['prod_cat2'].unique()

array([ 2.,  0., 11.,  5., 14.,  8., 17., 13.,  6., 16., 15.,  4.,  9.,
       10., 12.,  3., 18.,  7.])

In [50]:
df_1['prod_cat3'].unique()

array([ 0.,  5., 15., 14.,  6., 18.,  9., 17., 16.,  8., 10., 13., 12.,
        3., 11.,  4.])

In [55]:
df_1['prod_cat2'] = df_1['prod_cat2'].astype(int)
df_1['prod_cat3'] = df_1['prod_cat3'].astype(int)

In [59]:
df_1.loc[:,'category'] = df_1['prod_cat1'].astype(str) + '-' + df_1['prod_cat2'].astype(str) +'-' + df_1['prod_cat3'].astype(str)

In [60]:
df_1.head()

index  user  marital  prod_cat1  prod_cat2  prod_cat3 category
0      5     3        0          1          2          0    1-2-0
1      9     5        1          8          0          0    8-0-0
2     10     5        1          5         11          0   5-11-0
3     11     5        1          8          0          0    8-0-0
4     12     5        1          8          0          0    8-0-0

In [65]:
df_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 219587 entries, 0 to 219586
Data columns (total 7 columns):
 #   Column     Non-Null Count   Dtype 
---  ------     --------------   ----- 
 0   index      219587 non-null  int64 
 1   user       219587 non-null  int64 
 2   marital    219587 non-null  int64 
 3   prod_cat1  219587 non-null  int64 
 4   prod_cat2  219587 non-null  int64 
 5   prod_cat3  219587 non-null  int64 
 6   category   219587 non-null  object
dtypes: int64(6), object(1)
memory usage: 11.7+ MB


In [ ]:
df_1['category'].nunique()

In [108]:
#고객 별 카테고리 갯수
df_cust = df_1.groupby(['user','marital']).value_counts(['category']).reset_index()
df_cust = df_cust.groupby(['user','marital']).count()['category'].reset_index()
non_married = df_cust.groupby('marital')['category'].mean()[0]
married = df_cust.groupby('marital')['category'].mean()[1]
round(married - non_married,2)

0.13

In [ ]:
df_agg = df_1.groupby(['user','marital'])['category'].nunique().reset_index()
stat_m0 = df_agg.loc[df_agg['marital'] == 0, 'category'].mean()
stat_m1 = df_agg.loc[df_agg['marital'] == 1, 'category'].mean()
round(abs(stat_m0 - stat_m1),2)

In [109]:
#q3

In [110]:
df.head()

user       prod gender age_group  job city  marital  prod_cat1  prod_cat2  \
0     1  P00069042      F      0-17   10    A        0          3        NaN   
1     1  P00248942      F      0-17   10    A        0          1        6.0   
2     1  P00087842      F      0-17   10    A        0         12        NaN   
3     1  P00085442      F      0-17   10    A        0         12       14.0   
4     2  P00285442      M       55+   16    C        0          8        NaN   

   prod_cat3  purchase  
0        NaN      8370  
1       14.0     15200  
2        NaN      1422  
3        NaN      1057  
4        NaN      7969

In [ ]:
df_user = df[['user','gender','age_group','job','city','marital']].drop_duplicates().reset_index(drop=True)
df_user['user'].nunique(), len(df_user)

In [ ]:
df_agg = df.groupby('user')[['prod','purchase']].agg({'prod':'nunique',
                                                     'purchase':'sum'})
df_agg = df_agg.reset_index()
df_agg.head()

In [ ]:
df_q3 = df_user.merge(df_agg, on = 'user', how = 'inner')
df_q3 = df_q3.drop(columns = 'user')

In [ ]:
df_q3 = df_q3['gender'].replace({'M':1,'F':0})


In [ ]:
arr_u = df_q3['age_group'].unique()
arr_u.sort()

In [ ]:
ser_repl = pd.Series(range(7), index = arr_u)

In [ ]:
pd.crosstab(df_q3['age_group'], df_q3['age_group'].replace(ser_repl))


In [144]:
df_3 = df.fillna(0)
df_3['prod_cat1'] = df_3['prod_cat1'].astype(int)
df_3['prod_cat2']=df_3['prod_cat2'].astype(int)
df_3['prod_cat3']=df_3['prod_cat3'].astype(int)
df_3['prod'] = df_3['prod_cat1'].astype(str) + '-' + df_3['prod_cat2'].astype(str) +'-' + df_3['prod_cat3'].astype(str)
df_3.head()

user     prod gender age_group  job city  marital  prod_cat1  prod_cat2  \
0     1    3-0-0      F      0-17   10    A        0          3          0   
1     1   1-6-14      F      0-17   10    A        0          1          6   
2     1   12-0-0      F      0-17   10    A        0         12          0   
3     1  12-14-0      F      0-17   10    A        0         12         14   
4     2    8-0-0      M       55+   16    C        0          8          0   

   prod_cat3  purchase  
0          0      8370  
1         14     15200  
2          0      1422  
3          0      1057  
4          0      7969

In [145]:
df_33 = df_3.set_index(['user','prod'])
#df_3.loc[:,'prod_count'] = df_3.groupby('user').value_counts(['prod'])

In [146]:
df_33.loc[:,'prod_count'] = df_3.groupby('user').value_counts(['prod'])

In [148]:
df_33 = df_33.reset_index()

In [149]:
df_33.head()

user     prod gender age_group  job city  marital  prod_cat1  prod_cat2  \
0     1    3-0-0      F      0-17   10    A        0          3          0   
1     1   1-6-14      F      0-17   10    A        0          1          6   
2     1   12-0-0      F      0-17   10    A        0         12          0   
3     1  12-14-0      F      0-17   10    A        0         12         14   
4     2    8-0-0      M       55+   16    C        0          8          0   

   prod_cat3  purchase  prod_count  
0          0      8370           1  
1         14     15200           1  
2          0      1422           2  
3          0      1057           1  
4          0      7969          18

In [150]:
df_a = df_33[['gender','age_group','job','city','marital','prod_count','purchase']]
df_a.head()

gender age_group  job city  marital  prod_count  purchase
0      F      0-17   10    A        0           1      8370
1      F      0-17   10    A        0           1     15200
2      F      0-17   10    A        0           2      1422
3      F      0-17   10    A        0           1      1057
4      M       55+   16    C        0          18      7969

In [151]:
df_a['age_group'].unique()

array(['0-17', '55+', '26-35', '46-50', '51-55', '36-45', '18-25'],
      dtype=object)

In [152]:
df_a['age_group'] = df_a['age_group'].apply(lambda x : 0 if x == '0-17'else 
                       (1 if x == '18-25' else 
                       (2 if x == '26-35' else 
                       (3 if x == '36-45' else 
                       (4 if x == '46-50' else 
                       (5 if x == '51-55' else 6)))))
                       )

/var/folders/08/qfhf2lxn7wlcym8tkm5j1t640000gn/T/ipykernel_85031/3201090016.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_a['age_group'] = df_a['age_group'].apply(lambda x : 0 if x == '0-17'else


In [153]:
df_a['gender'] = df_a['gender'].apply(lambda x : 0 if x == 'F' else 1)

/var/folders/08/qfhf2lxn7wlcym8tkm5j1t640000gn/T/ipykernel_85031/1242804258.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_a['gender'] = df_a['gender'].apply(lambda x : 0 if x == 'F' else 1)


In [154]:
df_a = pd.get_dummies(df_a,columns = ['job','city'])

In [155]:
df_a

gender  age_group  marital  prod_count  purchase  job_0  job_1  job_2  \
0            0          0        0           1      8370      0      0      0   
1            0          0        0           1     15200      0      0      0   
2            0          0        0           2      1422      0      0      0   
3            0          0        0           1      1057      0      0      0   
4            1          6        0          18      7969      0      0      0   
...        ...        ...      ...         ...       ...    ...    ...    ...   
550063       1          5        1           1       368      0      0      0   
550064       0          2        0           1       371      0      1      0   
550065       0          2        1           1       137      0      0      0   
550066       0          6        0           1       365      0      1      0   
550067       0          4        1           1       490      1      0      0   

        job_3  job_4  ...  job_14  job_15  job_16  job_17  job_18  job_19  \
0           0      0  ...       0       0       0       0       0       0   
1           0      0  ...       0       0       0       0       0       0   
2           0      0  ...       0       0       0       0       0       0   
3           0      0  ...       0       0       0       0       0       0   
4           0      0  ...       0       0       1       0       0       0   
...       ...    ...  ...     ...     ...     ...     ...     ...     ...   
550063      0      0  ...       0       0       0       0       0       0   
550064      0      0  ...       0       0       0       0       0       0   
550065      0      0  ...       0       1       0       0       0       0   
550066      0      0  ...       0       0       0       0       0       0   
550067      0      0  ...       0       0       0       0       0       0   

        job_20  city_A  city_B  city_C  
0            0       1       0       0  
1            0       1       0       0  
2            0       1       0       0  
3            0       1       0       0  
4            0       0       0       1  
...        ...     ...     ...     ...  
550063       0       0       1       0  
550064       0       0       0       1  
550065       0       0       1       0  
550066       0       0       0       1  
550067       0       0       1       0  

[550068 rows x 29 columns]

In [162]:
len(df_a.columns)

29

In [158]:
scaler = MinMaxScaler()
df_scaled = scaler.fit_transform(df_a)

In [163]:
kmeans = KMeans(n_clusters=7, random_state = 123)

In [164]:
kmeans.fit(df_scaled)

KMeans(n_clusters=7, random_state=123)

In [165]:
labels = kmeans.labels_

In [166]:
silhouette_score(df_scaled, labels)

0.17740679592435285

In [ ]:
df_scaled['cluster'] = labels
df_scaled['cluster'].value_counts() # 각 군집의 크기